sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"shalixiaohu\",\"password\":\"shalixiaohu\"}]"
  rabbitmq:
    host: 192.168.109.131
    port: 5672
    username: admin
    password: admin
spring:
  application:
    name: user-service
    111111111
    333333333
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka
111111